# When resolving inconsistencies, upper and lower bounds on the number of assets are required. The bounds are generated by sampling from the distributions N_SAMPLES_FOR_BOUNDS times.
N_SAMPLES_FOR_BOUNDS = 100
PLOT_FILE_NAME = 'plot.png'
