def sample_metamodel(size_factor = 10):
    metamodel_of_adjustable_size = {'network': {'abbreviation': 'N',
                                                'n': {'distribution': 'BinomialPlusOne',
                                                      'n': 1*size_factor,
                                                      'p': 0.5},
                                                'associated_assets': {
                                                    'network': {'distribution': 'BinomialPlusOne',
                                                                'n': 10,
                                                                'p': 0.1},
                                                    'vm_instance': {'distribution': 'Binomial',
                                                                    'n': 10*size_factor,
                                                                    'p': 0.05}},
                                                'visualization': {'shape': 's',
                                                                           'color': 'red'}},
                                    'vm_instance': {'abbreviation': 'VM',
                                                    'n': {'distribution': 'BinomialPlusOne',
                                                          'n': 5*size_factor,
                                                         'p': 0.5},
                                                    'associated_assets': {
                                                        'network': {'distribution': 'Constant',
                                                                    'n': 1},
                                                        'admin_privileges': {'distribution': 'Constant',
                                                                             'n': 1}},
                                                    'visualization': {'shape': 'o',
                                                                               'color': 'blue'}},
                                    'admin_privileges': {'abbreviation': 'A',
                                                         'n': {'distribution': 'BinomialPlusOne',
                                                               'n': 5*size_factor,
                                                               'p': 0.5},
                                                         'associated_assets': {
                                                             'vm_instance': {'distribution': 'Constant',
                                                                             'n': 1},
                                                             'principal': {'distribution': 'BinomialPlusOne',
                                                                           'n': 10,
                                                                           'p': 0.1}},
                                                         'visualization': {'shape': 'v',
                                                                                    'color': 'yellow'}},
                                    'principal': {'abbreviation': 'P',
                                                  'n': {'distribution': 'BinomialPlusOne',
                                                        'n': 10*size_factor,
                                                        'p': 0.05},
                                                  'associated_assets': {
                                                      'admin_privileges': {'distribution': 'Binomial',
                                                                           'n': 2*size_factor,
                                                                           'p': 0.1}},
                                                  'visualization': {'shape': '^',
                                                                             'color': 'green'}}}

    return metamodel_of_adjustable_size